name: Run on Self-Hosted Runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]  # more specific label match

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display environment info
        shell: pwsh
        run: |
          Write-Host "✅ Running on a self-hosted runner!"
          Write-Host "User: $env:USERNAME"
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"

      - name: Run sample script
        shell: pwsh
        run: |
          Write-Host "This is where your automation would go."
          Write-Host "For example, build your app or run tests."
