name: Run on Self-Hosted Runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Display environment info
        shell: pwsh
        run: |
          Write-Host "✅ Running on a self-hosted runner!"
          Write-Host "User: $env:USERNAME"
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"

      - name: Ru
