name: Blank Test

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/blank.yml"

jobs:
  test:
    runs-on: [self-hosted, windows]
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run with hardcoded PowerShell 7
        shell: '"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -Command'
        run: |
          Write-Host "✅ Running on a self-hosted runner!"
          Write-Host "User: $env:USERNAME"
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
          pwsh --version
