name: Blank Test

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/blank.yml"

jobs:
  test:
    runs-on: [self-hosted, windows]
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 pinned

      # Call PS7 by absolute path so we don't rely on PATH at all.
      - name: Run with PowerShell 7 (absolute path, heredoc)
        shell: powershell
        run: |
          $ps7 = 'C:\Program Files\PowerShell\7\pwsh.exe'
          if (-not (Test-Path $ps7)) {
            throw "PowerShell 7 not found at $ps7. Install PowerShell 7 or adjust the path."
          }

          # Show the PS7 version without relying on PATH inside PS7
          & $ps7 -NoLogo -NoProfile -NonInteractive -Command @'
            Write-Host "✅ Running on a self-hosted runner!"
            Write-Host "User: $env:USERNAME"
            Write-Host "Current directory: $(Get-Location)"
            Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
            Write-Host "PS7 Version: $($PSVersionTable.PSVersion)"
            Write-Host "PS7 Home: $PSHOME"
          '@
