name: Run on Self-Hosted Runner

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Allow PowerShell scripts for this job
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          Get-ExecutionPolicy -List

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pinned

      - name: Display environment info
        run: |
          Write-Host "✅ Running on a self-hosted runner!"
          Write-Host "User: $env:USERNAME"
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
          $PSVersionTable

      - name: Run sample script
        run: |
          Write-Host "This is where your automation would go."
          Write-Host "For example, build your app or run tests."
